modLoader = "javafml"
loaderVersion = "${loader_version_range}"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "wynnventory"
version = "${version}"
displayName = "Wynnventory"
authors = ""
description = ""
logoFile = "assets/icon-compressed.png"

[[dependencies.wynnventory]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"

[[dependencies.wynnventory]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version}"

[[dependencies.wynnventory]]
modId = "wynntils"
type = "required"
versionRange = "^${wynntils_version}"

[[mixins]]
config = "wynnventory.mixins.json"

[[mixins]]
config = "wynnventory.mixins.neoforge.json"
